import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, BadgeCheck, BookOpen, CircleHelp, Coins, Droplets, Leaf, Satellite, Sprout } from "lucide-react";

export const metadata: Metadata = {
  title: "Panduan Penggunaan KarbonTani",
  description: "Panduan menghitung insentif karbon, mengolah jerami tanpa bakar, dan memverifikasi lahan sawah di Pleret.",
};

const guides = [
  { number: "01", title: "Cara Menghitung Nilai Jerami (Kalkulator Karbon)", description: "Lihat estimasi manfaat tahunan berdasarkan luas lahan; angka merupakan model pilot.", icon: Coins, accent: "text-amber-300 bg-amber-400/10 border-amber-400/20", steps: ["Pilih 1 Kapling (0,1 ha), 0,5 Ha, atau 1 Ha. Geser slider atau masukkan luas sendiri.", "Baca estimasi insentif Rupiah, penghematan pupuk kimia, dan peningkatan hasil gabah per tahun.", "Total manfaat ekonomi menjumlahkan ketiga komponen; tinjau nilai estimasi bersama kelompok tani."] },
  { number: "02", title: "Praktik Zero-Burn & Pengomposan Jerami", description: "Kembalikan bahan organik ke tanah tanpa membakar sisa panen.", icon: Sprout, accent: "text-emerald-300 bg-emerald-400/10 border-emerald-400/20", steps: ["Setelah panen, potong atau cacah jerami agar lebih mudah diratakan dan terurai; jangan membakarnya.", "Hamparkan jerami dan aplikasikan mikroba pengurai sesuai petunjuk produk serta arahan penyuluh. Jaga kelembapannya.", "Terapkan irigasi berselang (AWD) sesuai kondisi tanah dan fase tanaman, dengan arahan penyuluh."] },
  { number: "03", title: "Validasi Lahan & Sinkronisasi Satelit NASA", description: "Cocokkan pengamatan tingkat kawasan dengan batas dan kondisi petak di lapangan.", icon: Satellite, accent: "text-sky-300 bg-sky-400/10 border-sky-400/20", steps: ["Lintasan Terra dan akuisisi Landsat mengikuti orbit; awan dan pemrosesan dapat mengubah ketersediaan citra.", "Pastikan titik koordinat dan poligon sawah Pleret sesuai batas petak yang disepakati kelompok tani.", "Cocokkan citra dan catatan lapangan pada periode yang sama. Anomali satelit adalah sinyal pemeriksaan, bukan bukti tunggal pembakaran."] },
  { number: "04", title: "Penyaluran Insentif Bersama Gapoktan", description: "Pencatatan kelompok membantu menelusuri verifikasi dan penyaluran insentif.", icon: BadgeCheck, accent: "text-orange-300 bg-orange-400/10 border-orange-400/20", steps: ["Petani dan pengurus mencatat petak, praktik zero-burn, dan bukti kegiatan untuk ditinjau bersama.", "Setelah kelayakan dan kredit karbon dikonfirmasi, skema pilot mengalokasikan 70% nilai kredit untuk petani. Estimasi bukan konfirmasi pencairan.", "Gapoktan merekap hak anggota dan menyalurkan bagian yang disetujui melalui rekening kelompok tani desa dengan catatan yang dapat diperiksa."] },
];

const faqs = [
  { question: "Apakah panduan bisa dibuka tanpa internet di ponsel?", answer: "Saat ini KarbonTani belum menyediakan mode offline. Buka halaman saat tersambung internet; simpan tangkapan layar bagian yang diperlukan." },
  { question: "Apa kriteria foto untuk verifikasi lahan?", answer: "Bukti yang berguna memperlihatkan jerami atau kompos dan konteks petak, dengan waktu serta lokasi yang bisa dicocokkan. Form verifikasi saat ini masih demo: belum mengambil foto sungguhan atau mengunggah bukti." },
  { question: "Bagaimana rumus estimasi manfaat dihitung?", answer: "Untuk A hektare per tahun: karbon Rp1.008.000 × A, hemat pupuk Rp1.000.000 × A, dan kenaikan hasil gabah Rp4.550.000 × A. Total adalah penjumlahan ketiganya; angka ini estimasi model." },
];

export default function PanduanPage() {
  return <main className="min-h-screen overflow-x-hidden bg-[#0F172A] px-3 py-4 text-white sm:px-6 sm:py-6 lg:px-8">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(ellipse_at_48%_-20%,rgba(16,185,129,0.12),transparent_55%)]" />
    <div className="relative mx-auto w-full max-w-5xl space-y-8 sm:space-y-10">
      <header className="flex flex-col gap-5 border-b border-slate-800 pb-5 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-emerald-400/20 bg-emerald-400/10 text-emerald-300"><BookOpen className="h-5 w-5" /></span><div><Link href="/" className="text-sm font-semibold text-slate-400 hover:text-white">Karbon<span className="text-[#FF6B00]">Tani</span></Link><p className="text-[10px] font-mono tracking-widest text-slate-500">PANDUAN PETANI · PLERET</p></div></div>
        <Link href="/" className="inline-flex min-h-11 w-fit max-w-full items-center gap-2 rounded-xl border border-slate-700 bg-slate-800/70 px-4 py-2.5 text-sm font-semibold text-slate-200 hover:border-emerald-400/40"><ArrowLeft className="h-4 w-4" />Kembali ke beranda</Link>
      </header>
      <section className="space-y-4"><span className="inline-flex max-w-full items-center gap-1.5 rounded-full border border-[#FF6B00]/25 bg-[#FF6B00]/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-orange-300"><Leaf className="h-3.5 w-3.5" />Dari sawah sehat menuju insentif terukur</span><h1 className="max-w-4xl break-words text-3xl font-black leading-tight sm:text-5xl">Panduan Penggunaan <span className="text-emerald-400">KarbonTani</span></h1><p className="max-w-3xl text-sm leading-relaxed text-slate-300 sm:text-base">Cara Menghitung Insentif Karbon, Mengolah Jerami Tanpa Bakar, dan Memverifikasi Lahan via Satelit</p></section>
      <section aria-labelledby="guides-title" className="space-y-4"><div className="border-b border-slate-800 pb-3"><p className="text-xs font-bold uppercase tracking-widest text-emerald-400">Empat langkah praktis</p><h2 id="guides-title" className="mt-1 text-xl font-bold sm:text-2xl">Dari pengelolaan jerami ke manfaat</h2></div><div className="space-y-3">
        {guides.map((guide) => { const Icon = guide.icon; return <details key={guide.number} className="group overflow-hidden rounded-2xl border border-slate-700/80 bg-slate-800/55 open:border-emerald-500/40"><summary className="flex min-h-20 cursor-pointer list-none items-center gap-3 p-4 sm:gap-4 sm:p-5 [&::-webkit-details-marker]:hidden"><span className="shrink-0 font-mono text-xs text-slate-500">{guide.number}</span><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border ${guide.accent}`}><Icon className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className="block break-words text-sm font-bold leading-snug sm:text-base">{guide.title}</span><span className="mt-1 block text-xs leading-relaxed text-slate-400">{guide.description}</span></span><span className="shrink-0 text-xl text-emerald-300 group-open:rotate-45">+</span></summary><div className="border-t border-slate-700/70 px-4 py-4 sm:px-6"><ol className="space-y-3">{guide.steps.map((step, index) => <li key={step} className="flex gap-3 text-sm leading-relaxed text-slate-300"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-emerald-500/10 text-xs text-emerald-300">{index + 1}</span><span>{step}</span></li>)}</ol></div></details>; })}
      </div></section>
      <section aria-labelledby="faq-title" className="grid gap-6 border-t border-slate-800 pt-7 sm:grid-cols-[0.75fr_1.25fr]"><div><CircleHelp className="h-8 w-8 text-[#FF6B00]" /><h2 id="faq-title" className="mt-3 text-xl font-bold sm:text-2xl">Pertanyaan umum</h2><p className="mt-2 text-sm text-slate-400">Akses, bukti lapangan, dan estimasi manfaat.</p></div><div className="divide-y divide-slate-700 border-y border-slate-700">{faqs.map((faq) => <details key={faq.question} className="group py-4"><summary className="flex cursor-pointer list-none gap-3 text-sm font-semibold"><span className="min-w-0 flex-1">{faq.question}</span><span className="text-lg text-emerald-300 group-open:rotate-45">+</span></summary><p className="mt-3 text-sm leading-relaxed text-slate-400">{faq.answer}</p></details>)}</div></section>
      <section className="flex flex-col gap-4 rounded-2xl border border-emerald-500/20 bg-emerald-500/[0.06] p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><Droplets className="mt-0.5 h-5 w-5 shrink-0 text-emerald-300" /><p className="text-sm leading-relaxed text-slate-300">Catat praktik di petak, lalu tinjau bersama Gapoktan dan penyuluh.</p></div><Link href="/#verification" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-emerald-400">Lihat verifikasi <ArrowUpRight className="h-4 w-4" /></Link></section>
      <footer className="flex flex-col gap-3 border-t border-slate-800 pt-5 text-xs text-slate-500 sm:flex-row sm:justify-between"><span>KarbonTani · Panduan pilot Pleret, Bantul</span><Link href="/sitemap.xml" className="w-fit hover:text-emerald-300">Sitemap</Link></footer>
    </div>
  </main>;
}
